# 向量(vector)

* 使用 `numpy` 的 `linalg` 模組的 `norm` 方法處理
> `np.linalg.norm(x, ord=None, axis=None, keepdims=False)`

* 從住家到公園的距離
> $$\sqrt{x^2 + y^2}$$

* 從商店到公司的距離
> $$\sqrt{(4 - 2)^2 + (4 - 1)^2}$$



In [1]:
import numpy as np
park = np.array([1, 3])
norm_park = np.linalg.norm(park)
norm_park

3.1622776601683795

![](pic.png)

## 切割一維陣列元素

* `Numpy` 陣列一樣可以使用 list 的切割運算子

In [5]:
a =  np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
b, c, d = a[1:3], a[:4], a[3:]
print(b, c, d)

[1 2 3 4 5 6 7 8 9]
[2 3] [1 2 3 4] [4 5 6 7 8 9]


* 在切割運算子共有3個參數，其餘法為:
> array[start:end:step]

上述「：」冒號分隔的值是`start`至`end`的範圍，`step`是增量，如下:

In [6]:
b, c, d = a[2:9:3], a[::2], a[::-1]
print(b, c, d)

[3 6 9] [1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


# 矩陣運算

* 矩陣與純量的四則運算
    - 矩陣與純量 (Scalar) 可以進行加減乘除的四則運算，純量是一個數值
    - 矩陣與純量適用 +, -, *, /

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 矩陣
print(a)
s = 5  # 純量
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [8]:
c =  a + s
print(c)
c =  a - s
print(c)
c =  a * s
print(c)
c =  a / s
print(c)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]]


* 如果有相同形狀的兩個矩陣，對應的矩陣元素也可以加減乘除

In [9]:
a = np.array([[1, 2],[3, 4]])
print(a)
s = np.array([[5, 6],[7, 8]])
print(s)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [10]:
c =  a + s
print(c)
c =  a - s
print(c)
c =  a * s
print(c)
c =  a / s
print(c)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## 點積(Dot Product)
* 是兩個矩陣對應元素的列和行的乘積和
* 矩陣a和s點積運算結果是另一個矩陣

![](pic1.png)

In [11]:
c = a.dot(s)
print(c)

[[19 22]
 [43 50]]


## 切割二微陣列的元素

* `NumPy`二維陣列一樣可以使用切割運算子，從原始陣列切割出所需的子 陣列，其語法如下所示：
> array[start:end:step, start1:end1:step1]

* 上述2個索引，分別都是開始、結束（不包含結束本身）和增量。
    - Q: 程式碼建立???陣列???~???後，使用reshape()方法轉換成二維陣列? X ?

In [12]:
a = np.arange(11, 36)
a = a.reshape(5, 5)
print(a)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


- A:程式碼建立一維陣列`11~36`後，使用`reshape()`方法轉換成二維陣列`5 x 5`
![](pic2.png)

* 第一個切割範例：二維陣列的列索引是0,0,0；欄索引是1,2,3，可以取出`[0,1]`、`[0,2]`和`[0,3]`的3個元素，如下所示：

In [13]:
b = a[0, 1:4]
print(b)

[12 13 14]


![](pic2.png)

* 第二個切割範例：二維陣列的列索引是1,2,3；欄索引是0,0,0，可以取出 [1,0]、[2,0]和[3,0]的3個元素，如下所示：

In [14]:
b = a[1:4, 0]
print(b)

[16 21 26]


![](pic2.png)

* 第三個切割範例：二維陣列的列索引是0,1；欄索引是1,2，可以取出 [0,1]、[0,2]、[1,1]和[1,2]的4個元素，如下所示：

In [15]:
b =  a[:2, 1:3]
print(b)

[[12 13]
 [17 18]]


![](pic2.png)

* 第四個切割範例：二維陣列的列索引是0,1,2,3,4；欄索引是1,1,1,1，可 以取出[0,1]、[1,1]、[2,1]、[3,1]和[4,1]的5個元素，如下所示：

In [16]:
b =  a[:, 1]
print(b)

[12 17 22 27 32]


![](pic2.png)

* 第五個切割範例：二維陣列的列索引是0,2,4；欄索引是0,2,4，可以取出 [0,0]、[0,2]、[0,4]、[2,0]、[2,2]、[2,4]、[4,0]、[4,2]和[4,4]的9個元素， 如下所示：

In [17]:
b = a[::2, ::2]
print(b)

[[11 13 15]
 [21 23 25]
 [31 33 35]]


![](pic2.png)

# 使用進階索引(INDEX)取出元素

* 使用整數值清單的索引
    - NumPy陣列不只可以使用整數值的索引來取出指定值，還可以給一個索引清單，取 出選擇的元素來建立一個新陣列

In [18]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
b = a[[1, 3, 5, 7]]    # 使用整數值清單的索引
print(b)

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


NumPy陣列還可以使用相同大小的布林值陣列，如果元素值是True，表示選擇對 應元素；反之False，就是不選擇

# 小練習:ARRAY的操作索引＆局部資料(切片)
### • **練習一**
- 線索: 
![](pic3.png)
- Q: 答案是甚麼??? ![](pic4.png)

* A: 答案是...... ![](pic5.png)

### • **練習二**
- 線索: 
![](pic3.png)
- Q: 答案是甚麼?!! 
![](pic7.png)

* A: 答案是......
![](pic6.png)

# 陣列形狀與內容操作

* 陣列平坦化的`ravel`方法可以將二維陣列平坦化成一維陣列
* `NumPy`還可以使用`.T`屬性或`transpose()`方法來交換陣列維度

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = a.ravel()    # 陣列攤平
print(b)
b = np.ravel(a)  # 陣列攤平
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [20]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b)
c = b.T  # 陣列轉置
print(c)
c = np.transpose(b)  # 陣列轉置, or "b.transpose()"
print(c)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


* 新增陣列的維度 
    - `NumPy`陣列的索引可以使用`np.newaxis`物件來新增陣列的維度，如下所示：

In [22]:
a = np.array([1, 2, 3])
print(a)
b = a[:, np.newaxis]  # 新增一個維度
print(b)
print(b.shape)

[1 2 3]
[[1]
 [2]
 [3]]
(3, 1)


* 陣列複製、填滿值和連接陣列
    - `NumPy`陣列可以使用`copy()`方法複製出1個內容完全相同的全新陣列`b`，如下所示：

In [23]:
b = a.copy()  # 陣列複製
print(b) 

[1 2 3]


*    - 陣列複製、填滿值和連接陣列 – `NumPy`陣列可以使用`copy()`方法複製出1個內容完全相同的全新陣列`b`，如下所示：

In [24]:
b.fill(4)  # 陣列填滿值
print(b)

[4 4 4]


* - 如果有多個`NumPy`陣列，可以使用`np.concatenate()`方法來連接多個陣列

In [25]:
c = np.concatenate((a, b))  # 連接陣列
print(c)

[1 2 3 4 4 4]


* 連接多個二維陣列
    - 在使用`np.concatenate()`方法連接多個二維陣列時，可以指定參數`axis`軸的連接方 向，參數值0是直向（預設值），可以連接在目前二維陣列的下方，如下所示：

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=0)  # 直向連接
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


* - `axis`軸的值1是橫向，每一個陣列是連接在目前陣列的右方，如下所示：

In [27]:
c = np.concatenate((a, b), axis = 1)  # 連接陣列
print(c)

[[1 2 5 6]
 [3 4 7 8]]
