# 向量(vector)

* 使用 `numpy` 的 `linalg` 模組的 `norm` 方法處理
> `np.linalg.norm(x, ord=None, axis=None, keepdims=False)`

* 從住家到公園的距離
> $$\sqrt{x^2 + y^2}$$

* 從商店到公司的距離
> $$\sqrt{(4 - 2)^2 + (4 - 1)^2}$$



In [3]:
import numpy as np
park = np.array([1, 3])
norm_park = np.linalg.norm(park)
norm_park

3.1622776601683795

![](pic.png)

## 切割一維陣列元素

* `Numpy` 陣列一樣可以使用 list 的切割運算子

In [5]:
a =  np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
b, c, d = a[1:3], a[:4], a[3:]
print(b, c, d)

[1 2 3 4 5 6 7 8 9]
[2 3] [1 2 3 4] [4 5 6 7 8 9]


* 在切割運算子共有3個參數，其餘法為:
> array[start:end:step]

上述「：」冒號分隔的值是`start`至`end`的範圍，`step`是增量，如下:

In [6]:
b, c, d = a[2:9:3], a[::2], a[::-1]
print(b, c, d)

[3 6 9] [1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


# 矩陣運算

* 矩陣與純量的四則運算
    - 矩陣與純量 (Scalar) 可以進行加減乘除的四則運算，純量是一個數值
    - 矩陣與純量適用 +, -, *, /

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 矩陣
print(a)
s = 5  # 純量
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [8]:
c =  a + s
print(c)
c =  a - s
print(c)
c =  a * s
print(c)
c =  a / s
print(c)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]]


* 如果有相同形狀的兩個矩陣，對應的矩陣元素也可以加減乘除

In [9]:
a = np.array([[1, 2],[3, 4]])
print(a)
s = np.array([[5, 6],[7, 8]])
print(s)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [10]:
c =  a + s
print(c)
c =  a - s
print(c)
c =  a * s
print(c)
c =  a / s
print(c)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## 點積(Dot Product)
* 是兩個矩陣對應元素的列和行的乘積和
* 矩陣a和s點積運算結果是另一個矩陣

![](pic1.png)

In [11]:
c = a.dot(s)
print(c)

[[19 22]
 [43 50]]


## 切割二微陣列的元素

* `NumPy`二維陣列一樣可以使用切割運算子，從原始陣列切割出所需的子 陣列，其語法如下所示：
> array[start:end:step, start1:end1:step1]

* 上述2個索引，分別都是開始、結束（不包含結束本身）和增量。
    - Q: 程式碼建立???陣列???~???後，使用reshape()方法轉換成二維陣列? X ?

In [12]:
a = np.arange(11, 36)
a = a.reshape(5, 5)
print(a)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


- A:程式碼建立一維陣列`11~36`後，使用`reshape()`方法轉換成二維陣列`5 x 5`
![](pic2.png)

* 第一個切割範例：二維陣列的列索引是0,0,0；欄索引是1,2,3，可以取出`[0,1]`、`[0,2]`和`[0,3]`的3個元素，如下所示：

In [13]:
b = a[0, 1:4]
print(b)

[12 13 14]


![](pic2.png)

* 第二個切割範例：二維陣列的列索引是1,2,3；欄索引是0,0,0，可以取出 [1,0]、[2,0]和[3,0]的3個元素，如下所示：

In [14]:
b = a[1:4, 0]
print(b)

[16 21 26]


![](pic2.png)

* 第三個切割範例：二維陣列的列索引是0,1；欄索引是1,2，可以取出 [0,1]、[0,2]、[1,1]和[1,2]的4個元素，如下所示：

In [15]:
b =  a[:2, 1:3]
print(b)

[[12 13]
 [17 18]]


![](pic2.png)

* 第四個切割範例：二維陣列的列索引是0,1,2,3,4；欄索引是1,1,1,1，可 以取出[0,1]、[1,1]、[2,1]、[3,1]和[4,1]的5個元素，如下所示：

In [16]:
b =  a[:, 1]
print(b)

[12 17 22 27 32]


![](pic2.png)

* 第五個切割範例：二維陣列的列索引是0,2,4；欄索引是0,2,4，可以取出 [0,0]、[0,2]、[0,4]、[2,0]、[2,2]、[2,4]、[4,0]、[4,2]和[4,4]的9個元素， 如下所示：

In [17]:
b = a[::2, ::2]
print(b)

[[11 13 15]
 [21 23 25]
 [31 33 35]]


![](pic2.png)

# 使用進階索引(INDEX)取出元素

* 使用整數值清單的索引
    - NumPy陣列不只可以使用整數值的索引來取出指定值，還可以給一個索引清單，取 出選擇的元素來建立一個新陣列

In [18]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
b = a[[1, 3, 5, 7]]    # 使用整數值清單的索引
print(b)

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


NumPy陣列還可以使用相同大小的布林值陣列，如果元素值是True，表示選擇對 應元素；反之False，就是不選擇

# 小練習:ARRAY的操作索引＆局部資料(切片)
### • **練習一**
- 線索: 
![](pic3.png)
- Q: 答案是甚麼??? ![](pic4.png)

* A: 答案是...... ![](pic5.png)

### • **練習二**
- 線索: 
![](pic3.png)
- Q: 答案是甚麼?!! 
![](pic7.png)

* A: 答案是......
![](pic6.png)

# 陣列形狀與內容操作

* 陣列平坦化的`ravel`方法可以將二維陣列平坦化成一維陣列
* `NumPy`還可以使用`.T`屬性或`transpose()`方法來交換陣列維度

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = a.ravel()    # 陣列攤平
print(b)
b = np.ravel(a)  # 陣列攤平
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [20]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b)
c = b.T  # 陣列轉置
print(c)
c = np.transpose(b)  # 陣列轉置, or "b.transpose()"
print(c)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


* 新增陣列的維度 
    - `NumPy`陣列的索引可以使用`np.newaxis`物件來新增陣列的維度，如下所示：

In [22]:
a = np.array([1, 2, 3])
print(a)
b = a[:, np.newaxis]  # 新增一個維度
print(b)
print(b.shape)

[1 2 3]
[[1]
 [2]
 [3]]
(3, 1)


* 陣列複製、填滿值和連接陣列
    - `NumPy`陣列可以使用`copy()`方法複製出1個內容完全相同的全新陣列`b`，如下所示：

In [23]:
b = a.copy()  # 陣列複製
print(b) 

[1 2 3]


*    - 陣列複製、填滿值和連接陣列 – `NumPy`陣列可以使用`copy()`方法複製出1個內容完全相同的全新陣列`b`，如下所示：

In [24]:
b.fill(4)  # 陣列填滿值
print(b)

[4 4 4]


* - 如果有多個`NumPy`陣列，可以使用`np.concatenate()`方法來連接多個陣列

In [25]:
c = np.concatenate((a, b))  # 連接陣列
print(c)

[1 2 3 4 4 4]


* 連接多個二維陣列
    - 在使用`np.concatenate()`方法連接多個二維陣列時，可以指定參數`axis`軸的連接方 向，參數值0是直向（預設值），可以連接在目前二維陣列的下方，如下所示：

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=0)  # 直向連接
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


* - `axis`軸的值1是橫向，每一個陣列是連接在目前陣列的右方，如下所示：

In [27]:
c = np.concatenate((a, b), axis = 1)  # 連接陣列
print(c)

[[1 2 5 6]
 [3 4 7 8]]


# 陣列廣播

* 陣列廣播
    - 廣播（`Broadcasting`）可以讓不同形狀的陣列執行數學運算。
    ![](pic8.png)

* 使用廣播執行陣列相加運算 
    - `NumPy`廣播可以計算二維陣列和一維陣列的加法運算 建立二維陣列`a（4 X 3）`和一維陣列`b`（尺寸3個元素）後，進行`a + b`的加法運算

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)
print("a 形狀: " + str(a.shape))
print("")
b = np.array([1, 0, 1])
print("-" *10)
print(b)
print("b 形狀: " + str(b.shape))
print("")
print("-"*10)
c = a + b  # 廣播機制
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a 形狀: (4, 3)

----------
[1 0 1]
b 形狀: (3,)

----------
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


![](pic9.png)

## NUMPY其他函數運算

In [8]:
x = np.arange(0, 100, 10, dtype=np.floating)
x

C:\Users\OwenLin\AppData\Local\Temp\ipykernel_10268\192390752.py:1: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  x = np.arange(0, 100, 10, dtype=np.floating)


array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
index = np.random.randint(0, len(x), size=5)
index

array([9, 5, 9, 5, 6])

In [12]:
x[index]

array([70., 80., 30., 90., 10.])

## Numpy 補充函式
* ### 相同維度

```python
"""(1)"""
index = np.random.randint(0,len(x),5) #隨機整數值[low,high)
index 
array([9, 5, 9, 5, 6]) 

"""(2)"""
noise = np.random.standard_normal(5)*0.3 #隨機雜訊 
noise 
array([ 0.07000973, 0.17404817, 0.16620985, 0.15281169, -0.08693726]) 

"""(3)"""
x[index] 
array([ 90., 50., 90., 50., 60.]) 

"""(4)"""
x[index] += noise #添加雜訊 
x[index] 
array([ 90.16620985, 50.15281169, 90.16620985, 50.15281169, 59.91306274]) 45 NUMPY其他函數運算 

"""(5)"""
x = np.arange(0, 100, 10, dtype=np.floating) 
np.sin(x) #一維陣列中所有元素求正弦值 
array([ 0. , -0.54402111, 0.91294525, -0.98803162, 0.74511316, -0.26237485, -0.30481062, 0.77389068, -0.99388865, 0.89399666]) 

"""(6)"""
b = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9])) 
np.cos(b) #二維陣列中所有元素求餘弦值 
array([[ 0.54030231, -0.41614684, -0.9899925 ], [-0.65364362, 0.28366219, 0.96017029], [ 0.75390225, -0.14550003, -0.91113026]]) 

"""(7)"""
np.round(_) #四捨五入 
array([[ 1., -0., -1.], [-1., 0., 1.], [ 1., -0., -1.]]) 

"""(8)"""
x = np.random.rand(10) # Random values in a given shape 
x 
array([0.82541802, 0.04283783, 0.11830544, 0.98540916, 0.58533409, 0.56195097, 0.97442386, 0.21045253, 0.62461573, 0.75924821]) 

"""(9)"""
x = x*10
X = np.array([18.25418018, 10.42837828, 1.18305441, 9.85409158, 5.85334093, 25.61950967, 49.74423864, 72.10452527, 6.24615732, 7.5924821 ]) 

"""(10)"""
np.floor(x) #所有元素向下取最大整數(無條件捨去小數點) 
array([18., 10., 1., 9., 5., 25., 49., 72., 6., 7.]) 

"""(11)"""
np.ceil(x) #所有元素向上取最小整數(無條件進位到整數) 
array([19., 11., 2., 10., 6., 26., 50., 73., 7., 8.])
```

* ### 指定不同維度


```python
"""(1)"""
>>> x = np.arange(0,10).reshape(2,5) #創建二維陣列
>>> x array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]) 
>>> np.sum(x) #二維陣列所有元素求和 
45 

"""(2)"""
>>> np.sum(x, axis=0) #二維陣列縱向求和 
array([ 5, 7, 9, 11, 13]) 

"""(3)"""
>>> np.sum(x, axis=1) #二維陣列橫向求和 
array([10, 35]) 

"""(4)"""
>>> np.mean(x, axis=0) #二維陣列縱向計算算術平均值 
array([ 2.5, 3.5, 4.5, 5.5, 6.5]) 

"""(5)"""
>>> weight = [0.3, 0.7] #設定權重 
>>> np.average(x, axis=0, weights=weight) #二維陣列縱向計算加權平均值 
array([ 3.5, 4.5, 5.5, 6.5, 7.5])

"""(6)"""
>>> np.max(x) #所有元素最大值 9 
>>> np.max(x, axis=0) #每列元素的最大值 
array([5, 6, 7, 8, 9]) 

"""(7)"""
>>> x = np.random.randint(0, 10, size=(3,3)) #創建二維陣列 
>>> x 
array([[4, 9, 1], [7, 4, 9], [8, 9, 1]]) 

"""(8)"""
>>> np.std(x) # 對所有元素算一個標準差 
3.1544599036840864 

"""(9)"""
>>> np.std(x, axis=1) #每行元素的標準差 
array([3.29983165, 2.05480467, 3.55902608]) 

"""(10)"""
>>> np.var(x, axis=0) #每列元素的變異數 
array([2.88888889, 5.55555556, 14.22222222])

"""(11)"""
>>> np.sort(x, axis=0) #縱向排序 
array([[4, 4, 1], [7, 9, 1], [8, 9, 9]]) 

"""(12)"""
>>> np.sort(x, axis=1) #橫向排序 
array([[1, 4, 9], [4, 7, 9], [1, 8, 9]])
```

## RESHAPE 改變陣列大小 

```python
"""(1)"""
>>> a = np.arange(1, 11, 1) 
>>> a 
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

"""(2)"""
>>> a.shape = 2, 5 #改為 2 行 5 列 
>>> a 
array([[ 1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10]]) 

"""(3)"""
>>> a.shape = 5, -1 # - 1表示自動計算 
>>> a 
array([[ 1, 2], [ 3, 4], [ 5, 6], [ 7, 8], [ 9, 10]]) 

"""(4)"""
>>> b = a.reshape(2, -1) #reshape()方法返回新陣列 
>>> b 
array([[ 1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10]])
```

## 只取小數 

```python
"""(1)"""
>>> x = np.random.rand(10)*50 
>>> x 
array([ 0.69708323, 14.99931488, 15.04431214, 24.60547929, 12.12020273, 42.72638176, 16.01128916, 38.91558471, 39.6877989 , 21.98678429]) 

"""(2)"""
>>> np.array([t-int(t) for t in x]) 
array([ 0.69708323, 0.99931488, 0.04431214, 0.60547929, 0.12020273, 0.72638176, 0.01128916, 0.91558471, 0.6877989 , 0.98678429])
```

## NUMPY基礎教學 

```python
"""(1)"""
>>> x 
array([0, 4, 3, 3, 8, 4, 7, 3, 1, 7])

"""(2)"""
>>> y 
array([0, 4, 3, 5, 6, 4, 1, 2, 1, 7]) 

"""(3)"""
>>> np.argmax(x) #最大值的索引 
4 

"""(4)"""
>>> np.where(x!=y)[0] #x!=y的地方 
array([3, 4, 6, 7]) 

"""(5)"""
>>> np.where(x<5, 0, 1) #小於5的元素值對應0，其他對應1 
array([[0, 0, 0, 0, 1, 0, 1, 0, 0, 1]]) 

"""(6)"""
#小於4的元素乘以2，大於7的元素乘以3，其他元素變為0 
>>> np.piecewise(x,[x<4, x>7],[lambda x:x*2,lambda x:x*3]) 
array([[ 0, 0, 6, 6, 24, 0, 0, 6, 2, 0]])
```
* #### 計算唯一值以及出現次數
```python
"""(1)"""
>>> x = np.random.randint(0,10,7) 
>>> x 
array([8, 7, 7, 5, 3, 8, 0]) 

"""(2)"""
>>> np.bincount(x) #元素出現次數，0出現1次 
array([1, 0, 0, 1, 0, 1, 0, 2, 2], dtype=int64) #1、2沒出現，3出現1次，以此類推 

"""(3)"""
>>> np.sum(a = 1) #所有元素出現次數之和等於陣列長度 
>>> len(x) 
>>> np.unique(x) #返回唯一元素值 
array([0, 3, 5, 7, 8])  

"""(4)"""
>>> x = numpy.random.randint(0,10,[2,7]) 
>>> x 
array([[4, 0, 3, 3, 7, 8, 5], [7, 3, 0, 9, 5, 1, 6]]) 

"""(5)"""
>>> x.flatten() #高維度矩陣平鋪
```